In [139]:
import pandas as pd
import os

df = pd.read_json('datasets/clientes_crm.json')
df.head()

,full_name,location,code,email
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com

In [140]:
df.rename(columns={'code': 'id_client'}, inplace=True)

In [141]:
df['email'] = df['email'].str.replace({'#': '@'}, regex=True)

In [142]:
df['location'] = df['location'].str.replace(r'[,/]', '-', regex=True)

In [143]:
df_split = df['location'].str.split('-', n=1, expand=True)

In [144]:
def ajustar_ordem(row):
    p1, p2 = row[0].strip(), row[1].strip() if row[1] else ""
    return (p2, p1) if len(p1) == 2 else (p1, p2)

In [145]:
df[['city', 'state']] = df_split.apply(ajustar_ordem, axis=1, result_type='expand')

In [146]:
df['city'] = df['city'].str.replace(r'\(.*?\)', '', regex=True).str.strip()

In [147]:
df['state'] = df['state'].str.upper()
df = df.drop('location',axis=1)

In [148]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  49 non-null     str
 1   id_client  49 non-null     int64
 2   email      49 non-null     str
 3   city       49 non-null     str
 4   state      49 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.0 KB

full_name    0
id_client    0
email        0
city         0
state        0
dtype: int64

In [149]:
df['city'] = df['city'].str.upper().str.strip()
df['state'] = df['state'].str.upper().str.strip()

In [150]:
verificar_tratamento_state = df[df['state'].str.len()!=2]
verificar_tratamento_state

Empty DataFrame
Columns: [full_name, id_client, email, city, state]
Index: []

In [151]:
pasta_destino = "CSVs tratados"
arquivo = 'clientes_tratados.csv'
caminho_completo = os.path.join(pasta_destino,arquivo)

In [152]:
if not os.path.exists(pasta_destino):
    os.makedirs(pasta_destino)

In [154]:
df_final = df.to_csv(caminho_completo,sep=';', index=False)