In [16]:
# Importando a biblioteca pandas para manipulação de dados
import pandas as pd
import os
# Lendo o arquivo JSON e armazenando em um DataFrame
df = pd.read_json("datasets/custos_importacao.json")
df.head()

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 105..."
1,2,Transponder Furuno Marlin,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 432..."
2,3,Radar Furuno Pulse Leviathan,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 254..."
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909..."
4,5,Piloto Automático Furuno Storm,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 600..."

In [17]:
# Explodindo a coluna 'historic_data' para criar uma linha para cada item da lista
df_explode_historic = df.explode('historic_data').reset_index(drop=True)

In [18]:
# Normalizando a coluna 'historic_data' para criar colunas separadas para cada chave do dicionário e 
# exibindo as primeiras linhas do DataFrame resultante
df_historic_data = pd.json_normalize(df_explode_historic['historic_data'])
df_historic_data.head()

   start_date  usd_price
0  10/08/2016   10583.63
1  15/06/2018    8778.36
2  25/09/2018    8023.87
3  19/03/2019    8772.78
4  17/01/2020    7918.18

In [19]:
# Concatenando o DataFrame original (sem a coluna 'historic_data') com o DataFrame normalizado para obter um DataFrame final
df_final = pd.concat([df_explode_historic.drop('historic_data', axis=1), df_historic_data], axis=1)

In [20]:
# Convertendo a coluna 'start_date' para o formato datetime, considerando o formato dia/mês/ano
df_final['start_date'] = pd.to_datetime(df_final['start_date'], dayfirst=True)

In [ ]:
# Exportando o DataFrame final para um arquivo CSV, sem o índice, usando ponto e vírgula como separador e codificação UTF-8
pasta_destino = 'CSVs_tratados'
arquivo = 'custo_importacao_tratados.csv'
caminho_completo = os.path.join(pasta_destino, arquivo)

In [22]:
# Verificando se a pasta de destino existe, e se não existir, criando-a
if not os.path.exists(pasta_destino):
    os.makedirs(pasta_destino)

In [23]:
# Exportando o DataFrame final para um arquivo CSV, sem o índice, usando ponto e vírgula como separador e codificação UTF-8
df_final.to_csv(caminho_completo, index=False, sep=";", encoding='utf-8-sig')
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   int64
 1   product_name  1260 non-null   str
 2   category      1260 non-null   str
 3   start_date    1260 non-null   datetime64[us]
 4   usd_price     1260 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 49.3 KB