In [27]:
# --- Sistema de Recomendação por Similaridade de Cosseno: 
# O modelo utiliza uma matriz para verificar a congruência em que dois produtos são vendidos na mesma compra ---
# Objetivo: Recomendação de produto para clientes novos.
# O arquivo segue uma organização de arquivos /cos_similaridade.ipynb
# /datasets/vendas_2023_2024.csv

# Importação das bibliotecas pandas para manipular dados e sklearn para construção da matriz
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Leitura do .csv de vendas
df = pd.read_csv('datasets/vendas_2023_2024.csv')

In [28]:
# Construção e Exibição da matriz comparando clientes e produtos
matriz = pd.crosstab(df['id_client'], df['id_product'])
matriz

id_product,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
id_client,,,,,,,,,,,,,,,,,,,,,
1,2,0,3,3,1,4,0,0,0,0,...,1,1,0,4,2,2,1,2,0,0
2,0,2,1,0,1,1,2,2,2,2,...,2,1,4,2,1,3,0,2,1,2
3,1,3,1,3,2,2,1,0,1,1,...,0,2,2,2,0,1,1,1,1,1
4,2,2,0,3,3,0,1,0,0,2,...,1,1,2,1,0,0,2,0,2,2
5,1,3,0,2,1,2,1,1,2,4,...,3,1,1,1,0,3,1,1,2,0
6,3,0,2,0,2,4,1,0,1,0,...,0,1,1,1,2,0,1,2,1,1
7,3,3,1,0,0,3,4,0,1,1,...,0,4,2,2,2,3,1,4,2,1
8,1,2,2,2,2,2,2,1,1,0,...,2,3,0,1,2,0,1,0,1,1
9,2,3,0,1,3,0,1,1,0,2,...,1,2,1,0,1,1,4,2,1,2
10,0,2,0,2,0,0,0,1,2,2,...,1,1,1,5,4,0,2,1,2,0
11,3,0,0,2,3,3,0,6,3,0,...,1,0,0,1,1,3,1,2,0,2
12,1,1,1,2,1,1,2,1,0,1,...,1,1,2,0,0,0,2,0,0,1
13,1,0,2,2,0,0,1,0,0,1,...,0,3,1,2,1,4,1,2,0,1
14,2,5,1,2,1,2,1,0,4,0,...,3,0,1,2,3,1,2,1,1,1
15,1,1,2,1,1,2,0,1,2,2,...,1,2,2,0,2,2,2,4,1,2
16,2,3,0,0,0,0,1,1,3,0,...,3,1,1,3,0,2,0,1,0,1
17,1,3,0,0,2,3,1,3,1,1,...,1,2,0,2,3,3,2,0,0,0
18,3,0,0,5,3,0,2,1,0,0,...,3,1,0,1,2,1,1,1,3,3
19,2,1,3,1,0,0,1,1,2,0,...,3,3,0,1,1,2,2,0,2,1
20,3,2,0,3,2,0,1,0,0,0,...,3,0,1,0,3,0,2,0,2,3
21,1,2,3,2,1,0,0,2,1,0,...,1,4,2,1,2,1,3,1,2,0
22,1,1,1,1,2,0,0,2,1,1,...,0,1,1,0,0,3,2,0,3,0
23,0,2,2,0,2,2,0,4,2,3,...,0,2,0,2,3,1,0,1,1,2
24,0,2,2,1,2,3,2,3,3,4,...,1,1,1,1,1,3,1,0,1,2
25,1,2,4,1,0,2,1,2,5,1,...,1,1,1,1,1,1,2,2,0,1
26,0,1,1,1,2,1,2,2,3,0,...,1,2,3,0,2,5,0,2,3,3
27,1,2,1,2,1,2,3,3,1,2,...,1,1,2,1,0,0,1,4,0,3
28,0,0,1,2,0,1,0,3,2,1,...,1,0,0,1,3,0,1,2,1,2
29,3,1,0,1,1,2,1,1,2,1,...,2,3,0,1,1,0,3,2,3,2
30,2,1,1,2,4,5,2,0,3,0,...,2,0,1,0,1,1,1,2,0,2
31,3,0,2,1,0,2,3,2,0,1,...,0,2,2,1,2,0,1,2,3,1
32,1,0,3,0,0,2,0,3,0,1,...,0,0,1,0,4,2,2,3,2,0
33,0,0,1,4,3,4,2,1,1,4,...,1,1,1,2,1,3,1,4,2,0
34,0,0,1,2,2,1,2,2,1,1,...,1,1,0,3,0,0,0,2,1,0
35,1,0,0,0,3,2,0,3,0,1,...,1,0,3,0,2,0,1,0,1,1
36,1,1,3,0,1,2,1,0,0,0,...,2,0,2,2,0,3,1,0,2,0
37,3,2,0,0,4,1,1,1,2,0,...,1,1,3,1,1,1,2,1,2,3
38,2,2,1,1,0,1,0,1,4,1,...,2,1,0,3,2,1,0,3,3,0
39,1,2,1,2,0,1,2,1,1,2,...,3,1,2,1,0,1,1,2,1,1
40,1,5,2,1,0,1,1,2,0,0,...,1,0,1,2,0,3,1,0,1,2
41,1,0,1,2,1,3,1,1,1,2,...,1,2,1,3,0,1,2,2,1,2
42,1,1,2,3,0,2,1,2,0,2,...,0,1,0,2,1,4,0,1,2,0
43,0,1,4,1,3,3,1,1,1,0,...,0,3,3,1,3,2,0,2,3,1
44,1,2,0,2,0,0,0,1,2,1,...,1,1,2,2,2,0,0,2,2,2
45,1,0,1,2,1,1,1,1,1,1,...,1,1,0,0,1,1,0,1,0,0
46,3,0,1,3,3,3,0,0,5,0,...,0,0,1,0,0,1,1,1,1,1
47,2,2,2,1,1,1,0,0,2,3,...,4,0,2,1,0,1,0,0,2,0
48,1,2,3,2,1,2,2,1,1,1,...,1,1,4,1,2,0,1,0,0,1
49,1,1,1,2,2,3,4,1,1,2,...,1,0,0,1,2,2,1,0,0,1

In [29]:
# Alteração de valores quantitativos para True ou False, usando 1 e 0
matriz_presenca = (matriz > 0).astype(int)
matriz_presenca

id_product,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
id_client,,,,,,,,,,,,,,,,,,,,,
1,1,0,1,1,1,1,0,0,0,0,...,1,1,0,1,1,1,1,1,0,0
2,0,1,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
3,1,1,1,1,1,1,1,0,1,1,...,0,1,1,1,0,1,1,1,1,1
4,1,1,0,1,1,0,1,0,0,1,...,1,1,1,1,0,0,1,0,1,1
5,1,1,0,1,1,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,0
6,1,0,1,0,1,1,1,0,1,0,...,0,1,1,1,1,0,1,1,1,1
7,1,1,1,0,0,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1
8,1,1,1,1,1,1,1,1,1,0,...,1,1,0,1,1,0,1,0,1,1
9,1,1,0,1,1,0,1,1,0,1,...,1,1,1,0,1,1,1,1,1,1
10,0,1,0,1,0,0,0,1,1,1,...,1,1,1,1,1,0,1,1,1,0
11,1,0,0,1,1,1,0,1,1,0,...,1,0,0,1,1,1,1,1,0,1
12,1,1,1,1,1,1,1,1,0,1,...,1,1,1,0,0,0,1,0,0,1
13,1,0,1,1,0,0,1,0,0,1,...,0,1,1,1,1,1,1,1,0,1
14,1,1,1,1,1,1,1,0,1,0,...,1,0,1,1,1,1,1,1,1,1
15,1,1,1,1,1,1,0,1,1,1,...,1,1,1,0,1,1,1,1,1,1
16,1,1,0,0,0,0,1,1,1,0,...,1,1,1,1,0,1,0,1,0,1
17,1,1,0,0,1,1,1,1,1,1,...,1,1,0,1,1,1,1,0,0,0
18,1,0,0,1,1,0,1,1,0,0,...,1,1,0,1,1,1,1,1,1,1
19,1,1,1,1,0,0,1,1,1,0,...,1,1,0,1,1,1,1,0,1,1
20,1,1,0,1,1,0,1,0,0,0,...,1,0,1,0,1,0,1,0,1,1
21,1,1,1,1,1,0,0,1,1,0,...,1,1,1,1,1,1,1,1,1,0
22,1,1,1,1,1,0,0,1,1,1,...,0,1,1,0,0,1,1,0,1,0
23,0,1,1,0,1,1,0,1,1,1,...,0,1,0,1,1,1,0,1,1,1
24,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
25,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
26,0,1,1,1,1,1,1,1,1,0,...,1,1,1,0,1,1,0,1,1,1
27,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,1,1,0,1
28,0,0,1,1,0,1,0,1,1,1,...,1,0,0,1,1,0,1,1,1,1
29,1,1,0,1,1,1,1,1,1,1,...,1,1,0,1,1,0,1,1,1,1
30,1,1,1,1,1,1,1,0,1,0,...,1,0,1,0,1,1,1,1,0,1
31,1,0,1,1,0,1,1,1,0,1,...,0,1,1,1,1,0,1,1,1,1
32,1,0,1,0,0,1,0,1,0,1,...,0,0,1,0,1,1,1,1,1,0
33,0,0,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0
34,0,0,1,1,1,1,1,1,1,1,...,1,1,0,1,0,0,0,1,1,0
35,1,0,0,0,1,1,0,1,0,1,...,1,0,1,0,1,0,1,0,1,1
36,1,1,1,0,1,1,1,0,0,0,...,1,0,1,1,0,1,1,0,1,0
37,1,1,0,0,1,1,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
38,1,1,1,1,0,1,0,1,1,1,...,1,1,0,1,1,1,0,1,1,0
39,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,1
40,1,1,1,1,0,1,1,1,0,0,...,1,0,1,1,0,1,1,0,1,1
41,1,0,1,1,1,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,1
42,1,1,1,1,0,1,1,1,0,1,...,0,1,0,1,1,1,0,1,1,0
43,0,1,1,1,1,1,1,1,1,0,...,0,1,1,1,1,1,0,1,1,1
44,1,1,0,1,0,0,0,1,1,1,...,1,1,1,1,1,0,0,1,1,1
45,1,0,1,1,1,1,1,1,1,1,...,1,1,0,0,1,1,0,1,0,0
46,1,0,1,1,1,1,0,0,1,0,...,0,0,1,0,0,1,1,1,1,1
47,1,1,1,1,1,1,0,0,1,1,...,1,0,1,1,0,1,0,0,1,0
48,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,0,0,1
49,1,1,1,1,1,1,1,1,1,1,...,1,0,0,1,1,1,1,0,0,1

In [30]:
# Fórmula para cálculo de similaridade na matriz
similarity = cosine_similarity(matriz_presenca.T)

In [31]:
# Formatação e Exibição dos valores de similaridades
df_similarity = pd.DataFrame(
    similarity, 
    index=matriz_presenca.columns, 
    columns=matriz_presenca.columns
)
df_similarity

id_product,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
id_product,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.775058,0.737865,0.810191,0.748331,0.769484,0.775058,0.727825,0.711512,0.698771,...,0.795133,0.753819,0.775058,0.769484,0.721605,0.775058,0.872082,0.721605,0.727825,0.775058
2,0.775058,1.000000,0.704295,0.757865,0.714286,0.712931,0.771429,0.750290,0.788811,0.687256,...,0.795192,0.778078,0.771429,0.767772,0.685714,0.742857,0.712931,0.628571,0.750290,0.742857
3,0.737865,0.704295,1.000000,0.800641,0.704295,0.865181,0.732467,0.712396,0.777778,0.707107,...,0.675923,0.739795,0.732467,0.757033,0.704295,0.788811,0.729996,0.732467,0.739795,0.704295
4,0.810191,0.757865,0.800641,1.000000,0.757865,0.753310,0.757865,0.789747,0.773953,0.735980,...,0.831239,0.789747,0.730798,0.779287,0.730798,0.730798,0.805263,0.757865,0.763422,0.757865
5,0.748331,0.714286,0.704295,0.757865,1.000000,0.795192,0.742857,0.694713,0.760639,0.627495,...,0.795192,0.722501,0.714286,0.685511,0.685714,0.714286,0.767772,0.657143,0.722501,0.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,0.775058,0.742857,0.788811,0.730798,0.714286,0.767772,0.714286,0.722501,0.760639,0.627495,...,0.712931,0.722501,0.714286,0.740351,0.714286,1.000000,0.712931,0.771429,0.722501,0.657143
147,0.872082,0.712931,0.729996,0.805263,0.767772,0.763158,0.767772,0.720064,0.702959,0.688247,...,0.789474,0.720064,0.795192,0.763158,0.740351,0.712931,1.000000,0.685511,0.746733,0.795192
148,0.721605,0.628571,0.732467,0.757865,0.657143,0.767772,0.685714,0.750290,0.788811,0.687256,...,0.685511,0.805867,0.714286,0.767772,0.771429,0.771429,0.685511,1.000000,0.750290,0.714286
149,0.727825,0.750290,0.739795,0.763422,0.722501,0.746733,0.694713,0.756757,0.739795,0.697486,...,0.720064,0.756757,0.778078,0.773402,0.722501,0.722501,0.746733,0.750290,1.000000,0.722501
150,0.775058,0.742857,0.704295,0.757865,0.714286,0.740351,0.800000,0.722501,0.732467,0.627495,...,0.740351,0.722501,0.771429,0.740351,0.742857,0.657143,0.795192,0.714286,0.722501,1.000000

In [32]:
# Determinação para produto alvo
produto_alvo = 27
# Atribuição para organizar os valores de similaridade em função do produto alvo
similares = df_similarity[produto_alvo].sort_values(ascending=False)

In [33]:
# Leitura da tabela de produtos tratados e renomeação da coluna 'code' para 'id_product'
df_produtos = pd.read_csv('produtos_raw_tratados.csv')
df_produtos.rename(columns={'code':'id_product'}, inplace=True)

In [34]:
# Junção e Exibição das tabelas com valor de similaridade e produtos
df_final = pd.merge(similares, df_produtos, on='id_product')
df_final.rename(columns={27:'similaridade'},inplace=True)
df_final

,id_product,similaridade,name,price,actual_category
0,27,1.000000,GPS Garmin Vortex Maré Drift,16511.45,eletrônicos
1,94,0.869626,Motor de Popa Volvo Magnum 276HP,40750.84,propulsão
2,11,0.868037,GPS Furuno Swift Leviathan Poseidon,36231.91,eletrônicos
3,35,0.853913,Radar Furuno Swift,11005.53,eletrônicos
4,115,0.850000,Cabo de Nylon Delta Force Magnum Leviathan,830.59,ancoragem
...,...,...,...,...,...
145,60,0.688102,Motor de Popa Honda Velocity Drift 258HP,108751.09,propulsão
146,120,0.688102,Boia de Arqueamento Danforth Flux Tidal,3124.49,ancoragem
147,43,0.675303,Sonda AIS Barracuda,35096.86,eletrônicos
148,75,0.675303,Motor Diesel Volvo Flow Leviathan Maré 187HP,32768.38,propulsão
149,95,0.653156,Motor Diesel Honda Leviathan 133HP,69808.04,propulsão

In [35]:
# Exibição dos 5 produtos que mais são comprados com o produto alvo GPS Garmin Vortex Maré Drift
print(f"Produtos que costumam sair junto com o product_id {produto_alvo}:")
df_final.iloc[0:6]

Produtos que costumam sair junto com o product_id 27:

,id_product,similaridade,name,price,actual_category
0,27,1.000000,GPS Garmin Vortex Maré Drift,16511.45,eletrônicos
1,94,0.869626,Motor de Popa Volvo Magnum 276HP,40750.84,propulsão
2,11,0.868037,GPS Furuno Swift Leviathan Poseidon,36231.91,eletrônicos
3,35,0.853913,Radar Furuno Swift,11005.53,eletrônicos
4,115,0.850000,Cabo de Nylon Delta Force Magnum Leviathan,830.59,ancoragem
5,1,0.850000,Transponder AIS Maré Magnum,33122.52,eletrônicos